# Paths
data_path: /Users/helenerousset/OneDrive - Capgemini/Documents/Illuin/squad1.1
train_filename: train-v1.1.json
test_filename: dev-v1.1.json

# Chosen dataset : train or test
dataset: train

# Model : TFIDF or BERT
model: BERT

# Indiquez si vous avez deja l'encodage des contextes et/ou des questions par le modele BERT
# load_question et question_pickle_name ne servent que pour le script d'Ã©valuation
# train question n'est pas sur git a cause de sa taille
load_context: true
context_pickle_name: train_context
load_question: true
question_pickle_name: train_question

# Metrics
rank: 10

# Inference question index (only for inference)
question_idx: 10
